{
  search(
    query: "repo:${repo} is:issue author:${username} created:${date_range}"
    type: ISSUE
    last: ${last}
  ) {
    edges {
      node {
        ... on Issue {
          title
          number
          url
        }
      }
    }
  }
}
