{
  search(
    query: "repo:${repo} is:pr is:merged merged:${date_range} author:${username}"
    type: ISSUE
    last: ${last}
  ) {
    edges {
      node {
        ... on PullRequest {
          title
          number
          url
        }
      }
    }
  }
}
